#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J multiqc
#SBATCH -t 1:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for getting a unique html report for different samples (RNA)
module load bioinfo-tools MultiQC

#run multiqc for both trimmed and untrimmed RNA samples
multiqc /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_fastqc_trimmed/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/preprocessing/RNA_fastqc_raw/ -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/multiQC/
