#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J assemblyeval
#SBATCH -t 10:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for evaluating the quality of assembly
#load the necessary modules
module load bioinfo-tools quast

#quast [options] <contig_file(s)>
metaquast.py -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/assembly/D1_eval /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D1/assembly_output_D1/final.contigs.fa
metaquast.py -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/assembly/D3_eval /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D3/assembly_output_D3/final.contigs.fa

