#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -J binning_eval
#SBATCH -t 05:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for quality of assembly
#prepare the analysis
#CheckM expects to be able to write to its local database directories, so you must install your own copy
cd /home/pcr98/GenomeAnalysis/GenomeAnalysis/output
mkdir CheckM_data
cd CheckM_data
#load the necessary modules
module load bioinfo-tools CheckM

#Download the data. The most recent data version as of this writing is 2015_01_16 from 2015/01/16
cp -av $CHECKM_DATA/checkm_data_2015_01_16.tar.gz .

#Unpack it into its own subdirectory
mkdir 2015_01_16
cd 2015_01_16
tar xzf ../checkm_data_2015_01_16.tar.gz

#tell CheckM about the data location
checkm data setRoot $PWD

#start the analysis
#Place bins in the reference genome tree --> checkm tree <bin folder> <output folder>
checkm tree -x fa --reduced_tree /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/
checkm tree -x fa --reduced_tree /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/


#Assess phylogenetic markers found in each bin --> checkm tree_qa <tree folder>
mkdir /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_tree_qa
mkdir /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_tree_qa 
checkm tree_qa /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/ -o 2 > /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_tree_qa/
checkm tree_qa /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/ -o 2 > /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_tree_qa/

#Infer lineage-specific marker sets for each bin -->  checkm lineage_set <tree folder> <marker file>
checkm lineage_set /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_marker
checkm lineage_set /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_marker 

#lineage_wf
checkm lineage_wf -t 4 -x fa --reduced_tree /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/
checkm lineage_wf -t 4 -x fa --reduced_tree /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/

#Identify marker genes in bins --> checkm analyze <marker file> <bin folder> <output folder>
mkdir /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_analyze
mkdir /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_analyze 
checkm analyze -x fa /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_marker /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_analyze/
checkm analyze -x fa /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_marker /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_analyze/

#Taxonomy pipeline --> taxon_set, analyze and qa --> checkm taxonomy_wf <results folder> <output folder>  
#checkm taxonomy_wf -t 2 -x fa domain Bacteria /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1 /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval 
#checkm taxonomy_wf -t 2 -x fa domain Bacteria /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3 /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval

#Assess bins for contamination and completeness --> checkm qa <marker file> <output folder>
checkm qa -t 2 -o 2 /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_marker /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_analyze > /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_qa.out
checkm qa -t 2 -o 2 /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_marker /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_analyze > /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_qa.out

#QA plot --> checkm bin_qa_plot <output folder> <results folder> <plot folder>
#checkm bin_qa_plot -x fa /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1_eval/D1_qa_plot
#checkm bin_qa_plot -x fa /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3_eval/D3_qa_plot





