#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J phylo
#SBATCH -t 10:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for phylogenetic reconstruction
#this script takes bins from binning without structural (Proka)/ functional (eggNOGmapper) annotation
#load the necessary modules
module load bioinfo-tools python biopython FasTree muscle usearch/5.2.32

#


