#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J phylo
#SBATCH -t 120:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for phylogenetic reconstruction
#this script takes bins from binning without structural (Proka)/ functional (eggNOGmapper) annotation
#load the necessary modules
module load bioinfo-tools phylophlan/0.99
module unload python
module load python/2.7.15 biopython/1.73 FastTree muscle/3.8.31 usearch/5.2.32

# Copy installed phylophlan 0.99 files to my working directory (couldnt download new version from bitbucket)
#cp -r /sw/bioinfo/phylophlan/0.99/snowy/bin/* /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/
#cp -r /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/* /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/ 
cd /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/
mkdir data
cd data
mkdir -p ppaalns
# symlink phylophlan data files
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/*.bz2 .
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppaalns/*.bz2 ppaalns/
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppafull.tax.txt .
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/taxcuration/ /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/taxcuration

 
# Prokka output will be the input for phylophlan since it has DNA/AA-sequence for the genes in the bins/genome (and metabat only had DNA-sequence for bins/genome)
ln -s /proj/genomeanalysis2022/nobackup/work/pcr/output/structann/D1/normalize/*ann.out/*.faa /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/input/D1/
ln -s /proj/genomeanalysis2022/nobackup/work/pcr/output/structann/D3/normalize/*ann.out/*.faa /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/input/D3/


#run phylophlan nproc -- number of CPUs -i input -o output with error file D1/D3_phylo.err
#/home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/phylophlan.py -i /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/*.fa -t --nproc 2 -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/output/D1/ 2> D1_phylo.err  
#/home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/phylophlan.py -i /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3/*.fa -t --nproc 2 -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/output/D3/ 2> D3_phylo.err
cd /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo 
phylophlan.py -i D1 -t --nproc 2 2> output/D1/D1_phylo.err
phylophlan.py -i D3 -t --nproc 2 2> output/D3/D3_phylo.err
