#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -J funct_ann
#SBATCH -t 120:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for functional annotation of bins using eggNOGmapper
#load the necessary modules
module load bioinfo-tools eggNOG-mapper

cd /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1 
for f in *
do
echo $f
#emapper.py -i FASTA_FILE_PROTEINS --itype type of data --output_dir output directory
emapper.py --itype metagenome -i $f -o $f --output_dir /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/functann/D1
done

cd /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3 
for f in *
do
echo $f
#emapper.py -i FASTA_FILE_PROTEINS --itype type of data --output_dir output directory
emapper.py --itype metagenome -i $f -o $f --output_dir /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/functann/D3
done

