#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J phylo
#SBATCH -t 10:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for phylogenetic reconstruction
#this script takes bins from binning without structural (Proka)/ functional (eggNOGmapper) annotation
#load the necessary modules
module load bioinfo-tools phylophlan python biopython FasTree muscle usearch/5.2.32


#rename files to not have the execution date
for D1_prokkabins in /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/structann/D1/*ann.out
do 
for D1_prokkafiles in $D1_prokkabins/*
do mv "$D1_prokkafiles" "${D1_prokkafiles//PROKKA_04112022/$D1_prokkabins}"
done
done

for D3_prokkabins in /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/structann/D3/*ann.out
do
for D3_prokkafiles in $D3_prokkabins/*
do mv "$D3_prokkafiles" "${D3_prokkafiles//PROKKA_04112022/$D3_prokkabins}"
done
done

# Copy installed phylophlan 0.99 files to my working directory (couldnt download new version from bitbucket)
cp -r /sw/bioinfo/phylophlan/0.99/snowy/bin/* /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/

# Prokka output will be the input for phylophlan since it has DNA/AA-sequence for the genes in the bins/genome (and metabat only had DNA-sequence for bins/genome)
ln -s /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/structann/D1/*ann.out/*.faa /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/input/D1/
ln -s /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/structann/D3/*ann.out/*.faa /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/input/D3/


#run phylophlan nproc -- number of CPUs -i input -o output with error file D1/D3_phylo.err
phylophlan.py --nproc 2 -i /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/input/D1/ -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/output/D1/ 2> D1_phylo.err  
phylophlan.py --nproc 2 -i /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/input/D3/ -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/phylo/output/D3/ 2> D3_phylo.err
