#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J normalize
#SBATCH -t 10:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for normalizing the assembly before binning: align trimmed DNA with contigs from assembly with BWA to get a depth for binning
#load the necessary modules
module load bioinfo-tools bwa samtools MetaBat

#sample D1
#BWA first needs to construct the FM-index for the reference genome (the index command) -- bwa index ref.fa
bwa index /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D1/assembly_output_D1/final.contigs.fa 2> /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1/D1_index.out

#Alignment algorithms are invoked with different sub-commands: aln/samse/sampe for BWA-backtrack, bwasw for BWA-SW and mem for the BWA-MEM algorithm -- bwa mem ref.fa read1.fq read2.fq > aln-pe.sam | Sort the alignments for later processing and store in a binary format -- samtools sort sample.sam -o sample.bam 
bwa mem /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D1/assembly_output_D1/final.contigs.fa /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/data/raw_data/DNA_trimmed/SRR4342129_1.paired.trimmed.fastq.gz /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/data/raw_data/DNA_trimmed/SRR4342129_2.paired.trimmed.fastq.gz  2> /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1/D1_mem.out | samtools sort -o /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D1/D1_sorted.bam #/domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1/D1_sorted.bam
#Index the sorted alignments to improve search speed -- samtools index sample.bam sample.bai
#samtools index /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1_sorted.bam D1_indexsam.bai

#Generate a depth file from BAM files -- jgi_summarize_bam_contig_depths --outputDepth depth.txt *.bam
jgi_summarize_bam_contig_depths --outputDepth /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D1/D1_depth.txt /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D1/*.bam
#jgi_summarize_bam_contig_depths --outputDepth /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1/D1_depth.txt /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1/*.bam

#run metabat -- binning with depth
cd /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D1
#cd /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1 
metabat -i /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D1/assembly_output_D1/final.contigs.fa -a D1_depth.txt --specific -l -v --saveTNF D1_saved.tnf --saveDistance D1_saved.gprob -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/normalize -t 2

#sample D3
#BWA first needs to construct the FM-index for the reference genome (the index command) -- bwa index ref.fa
bwa index /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D3/assembly_output_D3/final.contigs.fa 2> /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D3/D3_index.out

#Alignment algorithms are invoked with different sub-commands: aln/samse/sampe for BWA-backtrack, bwasw for BWA-SW and mem for the BWA-MEM algorithm -- bwa mem ref.fa read1.fq read2.fq > aln-pe.sam | Sort the alignments for later processing and store in a binary format -- samtools sort sample.sam -o sample.bam
bwa mem /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D3/assembly_output_D3/final.contigs.fa /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/data/raw_data/DNA_trimmed/SRR4342133_1.paired.trimmed.fastq.gz /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/data/raw_data/DNA_trimmed/SRR4342133_2.paired.trimmed.fastq.gz  2> /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D3/D3_mem.out | samtools sort -o /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D3/D3_sorted.bam
#Index the sorted alignments to improve search speed -- samtools index sample.bam sample.bai
#samtools index /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1_sorted.bam D1_indexsam.bai

#Generate a depth file from BAM files -- jgi_summarize_bam_contig_depths --outputDepth depth.txt *.bam
#jgi_summarize_bam_contig_depths --outputDepth /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D3/D3_depth.txt /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D3/*.bam
jgi_summarize_bam_contig_depths --outputDepth /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D3/D3_depth.txt /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D3/*.bam

#run metabat -- binning with depth
cd /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D3 
#cd /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D3
metabat -i /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D3/assembly_output_D3/final.contigs.fa -a D3_depth.txt --specific -l -v --saveTNF D3_saved.tnf --saveDistance D3_saved.gprob -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D3/normalize -t 2



  
