#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J qualitycheck
#SBATCH -t 1:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#script for running both quality check of trimmed DNA and not trimmed RNA: we need FastQC tool
#load the necessary modules
module load bioinfo-tools trimmomatic FastQC

#Apply trimmomatic to untrimmed RNA
#command java -jar <path to trimmomatic.jar> PE [-threads <threads] [-phred33 | -phred64] [-trimlog <logFile>] >] [-basein <inputBase> | <input 1> <input 2>] [-baseout <outputBase> | <unpaired output 1> <paired output 2> <unpaired output 2> <step 1> ...
#first sample of RNA
java -jar /sw/apps/bioinfo/trimmomatic/0.36/milou/trimmomatic-0.36.jar PE /home/pcr98/GenomeAnalysis/GenomeAnalysis/data/raw_data/RNA_untrimmed/SRR4342137.1.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/data/raw_data/RNA_untrimmed/SRR4342137.2.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trim_SRR4342137.forward_paired.trimmed.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trim_SRR4342137.forward_unpaired.trimmed.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trim_SRR4342137.reverse_paired.trimmed.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trim_SRR4342137.reverse_unpaired.trimmed.fastq.gz ILLUMINACLIP:/sw/apps/bioinfo/trimmomatic/0.36/milou/adapters/TruSeq3-PE.fa:2:30:10:2:keepBothReads LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

#second sample of RNA
java -jar /sw/apps/bioinfo/trimmomatic/0.36/milou/trimmomatic-0.36.jar PE /home/pcr98/GenomeAnalysis/GenomeAnalysis/data/raw_data/RNA_untrimmed/SRR4342139.1.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/data/raw_data/RNA_untrimmed/SRR4342139.2.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trim_SRR4342139.forward_paired.trimmed.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trim_SRR4342139.forward_unpaired.trimmed.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trim_SRR4342139.reverse_paired.trimmed.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trim_SRR4342139.reverse_unpaired.trimmed.fastq.gz ILLUMINACLIP:/sw/apps/bioinfo/trimmomatic/0.36/milou/adapters/TruSeq3-PE.fa:2:30:10:2:keepBothReads LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

#Check quality to trimmed RNA
for file in /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/preprocessing/RNA_trimmed/*
do
fastqc $file -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/preprocessing/RNA_fastqc_trimmed
done
