#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J binning
#SBATCH -t 10:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user paula.camargo-romera.7482@student.uu.se

#load the necessary modules
module load bioinfo-tools MetaBat

#run metabat -- binning with depth
cd /proj/genomeanalysis2022/nobackup/work/pcr/assembly/normalize/D1
#cd /domus/h1/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/normalize/D1
metabat -i /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/assembly/D1/assembly_output_D1/final.contigs.fa -a D1_depth.txt -p D1_paired.txt --specific -v --saveTNF D1_saved.tnf --saveDistance D1_saved.gprob -o /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/normalize/try/D1.normalize -t 2
